### ISSUE TITLE
swiftload

### ISSUE THREAD

**Issue by demex2008** [Gujal00/ResolveURL#871] opened 2024-08-22 23:41 UTC
Hello from Germany.
I have found a link  from the Filmpalst site

https://swiftload.io/v/8wbwz8lq0w

mfg.

**Comment by MrDini123** [comment] 2024-08-23 00:08
Hi,

The provided link resolves just fine for me. However there hasn't been a ResolveURL release yet since @Gujal00 ported swiftload. So wait for the release or drop the swiftload.py file manually to your kodi folder.

**Comment by Gujal00** [comment] 2024-08-23 00:26
Duplicate of #866  and #867

**Closed by Gujal00** 2024-08-23 00:26 UTC
Labels: duplicate
