### ISSUE TITLE
New resolvers needed please

### ISSUE THREAD

**Issue by dracosc22679** [Gujal00/ResolveURL#298] opened 2023-01-07 17:51 UTC
Hi. Is there any chance we can have dokicloud and rabbitstream resolvers?
Here are examples of links:
`https://dokicloud.one/embed-4/a0vXMkVyQf7o?z= (https://dokicloud.one/ajax/embed-4/getSources?id=a0vXMkVyQf7o)`
and
`https://rabbitstream.net/embed-4/tTiuvQLfsKpy?z= (https://rabbitstream.net/ajax/embed-4/getSources?id=tTiuvQLfsKpy)`

For the last link for example, i tried myself but i find this link '"sources":"U2FsdGVkX1/1x+7cM96P519QuBODr06jcnwDTJ+aQIZ+MVaJgLDgZo/QOSAsmXuhqVY9cPi/ff5Q0Gur56rGSO0CXK5X60+37CLuJiahU1yKGX+XTC9zOrIDyKLLax0D6WblVt4Ng3f2rK1fEdqiI3vpTKsM+9xeG84TAMfGInbdkvSJtpA15GBPTsRoiRYIn0QzLR9HtC5IrNhBTMnpzXA1lj9jGDUh7U2Kom/hPkftfGLesGSyNsA2qVGweTDOWHRJA8azlASRiLJrmbxtO0d4ATSD0Ki0tlFlO4ZvoD0Jj0geF+pbgiRE/LNc7e4a0XbQz1FXx1dxucMWpIekD+Wq3Mfhtpkm3rqhNGhhHBNLmWFqJ1COD9jSGsY4YHJfyTdMq7IJmASk3LiGUvJKRYYwBvCABZwSmKTFEXyd//zcccyGTPsLycvDxMwFk53RS0yVzputJE8wpJjANDpSTlE0y1WckGm17I0dRId4ukvZ1jy0dV1I9qORBgY/U77v/QrmEuir1GBhdElGztQxHCJETMpCrJphFZN8/Mt8Y32QpJnPHBdhEgkwxuY5ci+E"'  which i cannot use it as an m3u8 file!
Thanks

**Comment by Gujal00** [comment] 2023-01-08 03:39
Duplicate of #205 dokicloud, rapidstream, streamrapid are all the same site
The javascript is heavily obfuscated and changes every few hours, so cant be done in ResolveURL currently

**Comment by dracosc22679** [comment] 2023-01-08 08:32
Oh ok. Thanks

**Closed** 2024-05-12 20:55 UTC
Labels: duplicate, wontfix
