### ISSUE TITLE
FILEMOON plugin --> Video not found

### ISSUE THREAD

**Issue by repobal** [Gujal00/ResolveURL#966] opened 2024-12-18 16:15 UTC
Hello again.
We are developers of the Balandro addon and all logs are from Spain.

FILEMOON with GOOGLE CHROME exists and plays correctly; in All valid LINKS it ALWAYS gives this Result:

```python
2024-12-18 06:28:57.340 T:12828   error <general>: ResolveURL: ResolverError Error - From: FileMoon Link: https://filemoon.sx/e/4ldhmazuzt7c: Video not found
2024-12-18 06:28:57.375 T:12828   error <general>: ######## ERROR #########
2024-12-18 06:28:57.375 T:12828   error <general>:     [Balandro.servers.various.get_video_url] Traceback (most recent call last):
                                                     File "C:\Users\migue\AppData\Roaming\Kodi\addons\plugin.video.balandro\servers\various.py", line 208, in get_video_url
                                                       resuelto = resolveurl.resolve(page_url)
                                                     File "C:\Users\migue\AppData\Roaming\Kodi\addons\script.module.resolveurl\lib\resolveurl\__init__.py", line 133, in resolve
                                                       return source.resolve()
                                                     File "C:\Users\migue\AppData\Roaming\Kodi\addons\script.module.resolveurl\lib\resolveurl\hmf.py", line 205, in resolve
                                                       stream_url = resolver.get_media_url(self._host, self._media_id)
                                                     File "C:\Users\migue\AppData\Roaming\Kodi\addons\script.module.resolveurl\lib\resolveurl\plugins\filemoon.py", line 93, in get_media_url
                                                       raise ResolverError('Video not found')
                                                   resolveurl.resolver.ResolverError: Video not found
```

**Comment by Gujal00** [comment] 2024-12-18 18:49
Duplicate of #961

**Comment by Gujal00** [comment] 2024-12-19 20:31
Try with commit https://github.com/Gujal00/ResolveURL/commit/b4e559f1696469d97940086c6a7c848777ebb636
It could work for you

**Closed by Gujal00** 2024-12-19 20:31 UTC
Labels: duplicate
