### ISSUE TITLE
Failed to open settings.xml

### ISSUE THREAD

**Issue by Nagirah90** [Gujal00/ResolveURL#101] opened 2022-05-14 15:20 UTC
Hey,

I'm trying to auto update ResolveURL from within my plugin but whenever I do this, I get an error afterwards at script.module.resolveurl/lib/__init__.py line 256. It should check if that file exists before trying to open it.

Thank you!

**Comment by Gujal00** [comment] 2022-05-14 22:23
It is still an experimental feature and hasnt been released yet. Is your plugin pulling the git directly instead of release zip from smrzips repo?

**Comment by Nagirah90** [comment] 2022-05-16 09:48
Yes, I created a workflow that copies latest from your repository and creates a release that my plugin is accessing by commit hash. When kodi then tries to reload the scripts and gets to the import of ResolveURL, your script tries to update the settings and fails when accessing the non-existing settings.xml file in addon_data.

I temporarily put an additional import statement into my update code that is covered by a try/catch block so it doesn't break after an update but that's only a temporary solution. Your code should however check if addon_data contains a settings.xml before

**Comment by Gujal00** [comment] 2022-05-16 21:20
As you are pointing to a dev branch, you could run into broken installs all the time. By design the dev branch doesnt have an addons settings.xml file anyway and may keep wiping the users settings xml if installed directly. Not advisable at all. 
My release code will have testing done and released as the official zip

**Comment by Nagirah90** [comment] 2022-05-18 18:22
You should however not rely on a file that may or may not exist. This is simply bad coding style

**Comment by Gujal00** [comment] 2022-05-19 22:59
Either use the release version or if you insist on using dev version check everyday!
This was fixed the same day the issue was raised in https://github.com/Gujal00/ResolveURL/commit/40e8fe02eb456e819aa9f0546a2d62f29f0d870b

**Closed by Gujal00** 2022-05-19 22:59 UTC
